[package]
name = "zerofind"
version = "0.1.0"
edition = "2024"
authors = ["ZeroFind contributors"]
description = "A latency-first native Windows file finder"
license = "MIT"

[dependencies]
memchr = "2.8.3"
windows = { version = "0.58", features = ["Win32_UI_Controls", "Win32_Graphics_Gdi", "Foundation_Numerics", "Win32_Foundation", "Win32_Graphics_Direct2D", "Win32_Graphics_Direct2D_Common", "Win32_Graphics_DirectWrite", "Win32_Graphics_Dxgi_Common"] }

[lib]
name = "zerofind"
path = "src/lib.rs"

[[bin]]
name = "zerofind"
path = "src/main.rs"

[[bin]]
name = "spike_a"
path = "src/bin/spike_a.rs"

[[bin]]
name = "spike_b"
path = "src/bin/spike_b.rs"

[[bin]]
name = "spike_c"
path = "src/bin/spike_c.rs"

[profile.release]
codegen-units = 1
lto = "thin"
opt-level = 3
panic = "abort"
strip = "symbols"
